lightgbm:
  max_iter: 300
  learning_rate: 0.05
  max_depth: 10
  min_samples_leaf: 10
  random_state: 12345
logistic_regression:
  max_iter: 10000
  C: 1000
  random_state: 12345
random_forest:
  n_estimators: 300
  max_depth: 10
  min_samples_leaf: 10
  random_state: 12345
